# $FreeBSD: head/editors/libreoffice/Makefile.common 513051 2019-09-27 17:56:27Z lwhsu $

PORTNAME=	libreoffice
CATEGORIES+=	editors

MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL20
LICENSE_COMB=	dual

DISTVERSION=	7.0.0
DISTVERSIONSUFFIX=	.0.alpha1

PRERELEASE=	yes
DEVRELEASE=	yes
